server:
  port: 8300
  
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka  
      
spring:
  datasource:
    driver-class-name: com.yc.cj.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1/crbook
    username: root
    password: root      